# https://beta.ruff.rs/docs/rules/
select = [
    'A', # flake8-builtins
    'ARG', # flake8-unused-arguments
    'B', # flake8-bugbear
    'C4', # flake8-comprehensions
    'E', # pycodestyle
    'F', # pyflakes
    'PIE', # flake8-pie
    'PL', # pylint
    'PTH', # flake8-use-pathlib
    'RET', # flake8-return
    'RUF', # ruff
    'S', # flake8-bandit
    'SIM', # flake8-simplify
    'SLF', # flake8-self
    'UP', # pyupgrade
    'W', # pycodestyle
]
ignore = [
    'S603', # subprocess-without-shell-equals-true
    'S607', # start-process-with-partial-path
]
target-version = 'py38'
