# Run shellcheck and shfmt                                                                                                                                                                                                                                    ▎     ▎
name: Lint Checks
on:
  push:
    paths-ignore:
      - '**.py'
  pull_request:
    paths-ignore:
      - '**.py'
jobs:
  shellcheck:
    uses: ClangBuiltLinux/actions-workflows/.github/workflows/shellcheck.yml@main
  shfmt:
    uses: ClangBuiltLinux/actions-workflows/.github/workflows/shfmt.yml@main
